### ISSUE TITLE
[Missing] Right click for precision moving on Move Frames [FIXED!]

### ISSUE THREAD

**Issue by TheBloodEagle** [failcoder/SVUI-Kit#2]
I am honored to get the first one in! When you go to Move Frames, everything can be dragged, but if you right click a frame for precision moving, nothing happens.

Attempted relog, and reloading of UI with no success.

**Comment by failcoder** [comment]
Fixed, please re-test

**Comment by TheBloodEagle** [comment]
Still not working. When in Move Frames mode, and right clicking, I can hear the click, but the precision box is not popping up.

Also, on the subject of the Move Frames option, I never did tell you that when you click Grid, if you have multiple monitors, the grid is split into two sections. The part of the grid with the horizontal green line is on the center screen, and the 2nd overlay of the grid with the vertical green line is actually separated and on the far right monitor. Just FYI

**Comment by ghost** [comment]
Yep issue is still borked, would be great to get this back so I can get my UI completely back to how I had it in the old layout.

**Comment by failcoder** [comment]
Just fixed (and tested). Grab latest and be sure to remove all previous addon files

**Comment by TheBloodEagle** [comment]
Confirmed as fixed!
