### ISSUE TITLE
[Bug] Blizzard/SVUI blocking twitter functionality; has error

### ISSUE THREAD

**Issue by penguinsane** [failcoder/SVUI-Kit#75]
```
4x ...rfaceBlizzard_SocialUI\Blizzard_SocialUI-1.0.lua:119: Attempt to access forbidden object from code tainted by an AddOn
[C]: in function `Show'
...rfaceBlizzard_SocialUI\Blizzard_SocialUI-1.0.lua:119: in function `SocialPostFrame_ShowScreenshot'
FrameXML\ItemRef.lua:249: in function <FrameXML\ItemRef.lua:1>
[C]: ?
...aceBlizzard_CombatLog\Blizzard_CombatLog.lua:3602: in function `SetItemRef'
FrameXML\ChatFrame.lua:3374: in function <FrameXML\ChatFrame.lua:3373>
(tail call): ?
[C]: in function `ChatFrame_OnHyperlinkShow'
SVUI_Chat\SVUI_Chat-r20150224202648.lua:395: in function <SVUI_Chat\SVUI_Chat.lua:375>

Locals:
index = 1
```

**Comment by penguinsane** [comment]
Also:

```
1x ...rfaceBlizzard_SocialUI\Blizzard_SocialUI-1.0.lua:109: Attempt to access forbidden object from code tainted by an AddOn
[C]: in function `Show'
...rfaceBlizzard_SocialUI\Blizzard_SocialUI-1.0.lua:109: in function `SocialPostFrame_ShowAchievement'
FrameXML\ItemRef.lua:254: in function <FrameXML\ItemRef.lua:1>
[C]: ?
...aceBlizzard_CombatLog\Blizzard_CombatLog.lua:3602: in function `SetItemRef'
FrameXML\ChatFrame.lua:3374: in function <FrameXML\ChatFrame.lua:3373>
(tail call): ?
[C]: in function `ChatFrame_OnHyperlinkShow'
SVUI_Chat\SVUI_Chat-r20150224202648.lua:395: in function <SVUI_Chat\SVUI_Chat.lua:375>

Locals:
achievementID = 1182
earned = true
```

**Comment by penguinsane** [comment]
Just a heads up, getting a different error than before. Still can't click the "share" button next to options on screencapture/achievements/etc.

Not sure if this is directly related to SVUI, since I don't see it in the error, but it's worth mentioning.

```
1x ...rfaceBlizzard_SocialUI\Blizzard_SocialUI-1.0.lua:119: Attempt to access forbidden object from code tainted by an AddOn
[C]: in function `Show'
...rfaceBlizzard_SocialUI\Blizzard_SocialUI-1.0.lua:119: in function `SocialPostFrame_ShowScreenshot'
FrameXML\ItemRef.lua:249: in function <FrameXML\ItemRef.lua:1>
[C]: ?
...aceBlizzard_CombatLog\Blizzard_CombatLog.lua:3602: in function `SetItemRef'
FrameXML\ChatFrame.lua:3374: in function <FrameXML\ChatFrame.lua:3373>
(tail call): ?
[C]: in function `ChatFrame_OnHyperlinkShow'
[string "*:OnHyperlinkClick"]:1: in function <[string "*:OnHyperlinkClick"]:1>
[C]: ?
[C]: ?

Locals:
index = 1
```

**Comment by failcoder** [comment]
This should be fixed

**Comment by penguinsane** [comment]
It's not. Still getting an error. Not sure where it's coming from though, but I can use it if I disable SVUI.

```
1x ...rfaceBlizzard_SocialUI\Blizzard_SocialUI-1.0.lua:114: Attempt to access forbidden object from code tainted by an AddOn
[C]: in function `Show'
...rfaceBlizzard_SocialUI\Blizzard_SocialUI-1.0.lua:114: in function `SocialPostFrame_ShowItem'
FrameXML\ItemRef.lua:259: in function <FrameXML\ItemRef.lua:1>
[C]: ?
...aceBlizzard_CombatLog\Blizzard_CombatLog.lua:3602: in function `SetItemRef'
FrameXML\ChatFrame.lua:3374: in function <FrameXML\ChatFrame.lua:3373>
(tail call): ?
[C]: in function `ChatFrame_OnHyperlinkShow'
[string "*:OnHyperlinkClick"]:1: in function <[string "*:OnHyperlinkClick"]:1>
[C]: ?
[C]: ?

Locals:
itemID = "86132"
creationContext = ""
earned = true
```

**Comment by penguinsane** [comment]
To clarify, can't click the twitter icon. Can type and use /share just fine.
